version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    restart: unless-stopped