version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    restart: unless-stopped
    volumes:
      - ./src/quarkus-realm.json:/opt/keycloak/data/import/quarkus-realm.json