apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configmap
data:
  radar.datasource.username: radar
  radar.datasource.jdbc.url: jdbc:postgresql://postgres-service:5432/radar?ApplicationName=radar
  kc.datasource.jdbc.url: jdbc:postgresql://postgres-service:5432/keycloak?ApplicationName=keycloak
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  radar.datasource.password: YWlzdXJmZ2gzNDk4N3Ro
  radar.kc.password: WjIzZDc2YW93a2NzaWZ1ZUQ=
