-- VERSIONS
INSERT INTO versions (name, description, technology_id)
VALUES ('MariaDB 11.4.6', 'MariaDB Community Server 11.4.6 ist die neueste stabile Version mit langfristigem Support.',
        (SELECT id FROM technologies WHERE name = 'MariaDB')),
       ('Hibernate ORM 6.6.13.Final',
        'Hibernate ORM 6.6.13.Final wurde am 13. Mai 2025 veröffentlicht und bietet zahlreiche Verbesserungen.',
        (SELECT id FROM technologies WHERE name = 'Hibernate')),
       ('PostgreSQL 17.5',
        'PostgreSQL 17.5 wurde am 8. Mai 2025 veröffentlicht und enthält wichtige Sicherheitsupdates.',
        (SELECT id FROM technologies WHERE name = 'PostgreSQL')),
       ('Grafana 12.0.0',
        'Grafana 12.0.0 wurde am 7. Mai 2025 veröffentlicht und bietet neue Funktionen für die Datenvisualisierung.',
        (SELECT id FROM technologies WHERE name = 'Grafana')),
       ('Neo4j 2025.04.0',
        'Neo4j 2025.04.0 wurde am 30. April 2025 veröffentlicht und enthält wichtige Fehlerbehebungen.',
        (SELECT id FROM technologies WHERE name = 'Neo4J')),
       ('PostgreSQL 9.4', 'Die JSONB-Datentypunterstützung wurde in PostgreSQL 9.4 eingeführt.',
        (SELECT id FROM technologies WHERE name = 'JSONB')),
       ('MongoDB 8.0.8', 'MongoDB 8.0.8 ist die neueste stabile Version mit erweiterten Funktionen.',
        (SELECT id FROM technologies WHERE name = 'MongoDB')),
       ('Redis 8.0.0', 'Redis 8.0.0 wurde im April 2025 veröffentlicht und bietet zahlreiche Leistungsverbesserungen.',
        (SELECT id FROM technologies WHERE name = 'Redis')),
       ('RabbitMQ 4.1.0',
        'RabbitMQ 4.1.0 wurde am 15. April 2025 veröffentlicht und enthält neue Funktionen für Kubernetes.',
        (SELECT id FROM technologies WHERE name = 'RabbitMQ')),
       ('DDD 1.0', 'Domain-Driven Design ist ein konzeptioneller Ansatz ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'DDD')),
       ('TDD 1.0', 'Test-Driven Development ist eine Entwicklungsmethodik ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'TDD')),
       ('Cypress 14.3.3',
        'Cypress 14.3.3 wurde am 6. Mai 2025 veröffentlicht und bietet Verbesserungen für End-to-End-Tests.',
        (SELECT id FROM technologies WHERE name = 'Cypress')),
       ('Scrum Guide 2020', 'Der Scrum Guide 2020 ist die aktuelle Version des Scrum Frameworks.',
        (SELECT id FROM technologies WHERE name = 'Scrum')),
       ('TestRail 7.5', 'TestRail 7.5 ist die neueste Version des Testmanagement-Tools.',
        (SELECT id FROM technologies WHERE name = 'TestRail')),
       ('ADR 2.0', 'Architectural Decision Records Version 2.0 bietet strukturierte Entscheidungsdokumentation.',
        (SELECT id FROM technologies WHERE name = 'ADR')),
       ('Figma 123.0', 'Figma Version 123.0 bietet neue Funktionen für kollaboratives Design.',
        (SELECT id FROM technologies WHERE name = 'Figma')),
       ('Confluence 8.5', 'Confluence 8.5 ist die neueste Version der Dokumentationsplattform.',
        (SELECT id FROM technologies WHERE name = 'Confluence')),
       ('Jira 9.12', 'Jira 9.12 ist die aktuelle Version des Projektmanagement-Tools.',
        (SELECT id FROM technologies WHERE name = 'Jira')),
       ('TechRadar 1.0', 'TechRadar 1.0 ist die initiale Version des internen Visualisierungstools.',
        (SELECT id FROM technologies WHERE name = 'TechRadar')),
       ('Arc42 Template 8.0', 'Arc42 Template Version 8.0 bietet aktualisierte Architektur-Dokumentationsvorlagen.',
        (SELECT id FROM technologies WHERE name = 'Arc42')),
       ('NewRelic 10.0', 'NewRelic 10.0 ist die neueste Version der APM-Plattform.',
        (SELECT id FROM technologies WHERE name = 'NewRelic')),
       ('Sentry 23.4.1', 'Sentry 23.4.1 bietet erweiterte Fehlerverfolgung und Monitoring.',
        (SELECT id FROM technologies WHERE name = 'Sentry')),
       ('Kibana 8.9.0', 'Kibana 8.9.0 ist die aktuelle Version des Visualisierungstools für Elasticsearch.',
        (SELECT id FROM technologies WHERE name = 'Kibana')),
       ('ScanMeter 2.1', 'ScanMeter 2.1 ist die neueste Version des internen Metrik-Scanning-Tools.',
        (SELECT id FROM technologies WHERE name = 'ScanMeter')),
       ('Trunk Based Development 1.0',
        'Trunk Based Development ist ein Branching-Modell ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'Trunk Based')),
       ('FeatureToggle 3.2', 'FeatureToggle 3.2 bietet erweiterte Funktionen zur Feature-Steuerung.',
        (SELECT id FROM technologies WHERE name = 'FeatureToggle')),
       ('Continuous Delivery 2.5',
        'Continuous Delivery 2.5 umfasst aktuelle Praktiken und Tools für kontinuierliche Auslieferung.',
        (SELECT id FROM technologies WHERE name = 'ContDelivery')),
       ('GraphQL 16.6.0', 'GraphQL 16.6.0 ist die neueste Version der API-Abfragesprache.',
        (SELECT id FROM technologies WHERE name = 'GrpaphQL')),
       ('Altair GraphQL 5.0.0', 'Altair GraphQL 5.0.0 ist die aktuelle Version des GraphQL-Clients.',
        (SELECT id FROM technologies WHERE name = 'Altair GrpaphQL')),
       ('REST 1.0', 'REST ist ein Architekturstil ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'REST')),
       ('OpenAPI 3.1.0', 'OpenAPI 3.1.0 ist die neueste Spezifikation zur Definition von REST-APIs.',
        (SELECT id FROM technologies WHERE name = 'OpenAPI')),
       ('SOAP 1.2', 'SOAP 1.2 ist die aktuelle Version des XML-basierten Messaging-Protokolls.',
        (SELECT id FROM technologies WHERE name = 'SOAP')),
       ('SharedDB Pattern 1.0', 'SharedDB ist ein Architekturpattern ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'SharedDB')),
       ('RBAC 2.0', 'Role-Based Access Control Version 2.0 bietet erweiterte Zugriffssteuerung.',
        (SELECT id FROM technologies WHERE name = 'RBAC')),
       ('ABAC 1.0', 'Attribute-Based Access Control ist ein Zugriffssteuerungsmodell ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'ABAC')),
       ('OpenID Connect 1.0', 'OpenID Connect 1.0 ist die aktuelle Authentifizierungsschicht über OAuth 2.0.',
        (SELECT id FROM technologies WHERE name = 'OpenID Connect')),
       ('OAuth 2.1', 'OAuth 2.1 ist die neueste Version des Autorisierungsframeworks.',
        (SELECT id FROM technologies WHERE name = 'OAuth')),
       ('JWT 1.0', 'JSON Web Token ist ein kompaktes Token-Format ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'jwt')),
       ('Certificate-Based Auth 1.0',
        'Zertifikatsbasierte Authentifizierung ist ein Sicherheitsmechanismus ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'CertBased Auth')),
       ('Strangler Pattern 1.0', 'Das Strangler Pattern ist ein Migrationsansatz ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'Strangler')),
       ('FeatureFlag 3.2', 'FeatureFlag 3.2 bietet erweiterte Funktionen zur Feature-Steuerung.',
        (SELECT id FROM technologies WHERE name = 'FeatureFlag')),
       ('Citadelle Framework 1.0', 'Citadelle ist ein internes Architekturframework ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'Citadelle')),
       ('API Gateway Pattern 1.0', 'Das API Gateway Pattern ist ein Architekturansatz ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'Gateway')),
       ('Microservices Architecture 1.0',
        'Microservices Architecture ist ein Architekturansatz ohne spezifische Versionierung.',
        (SELECT id FROM technologies WHERE name = 'Microservice')),
       ('JIB 3.3.1', 'JIB 3.3.1 ist die neueste Version zum Erstellen von Container-Images für Java-Anwendungen.',
        (SELECT id FROM technologies WHERE name = 'JIB')),
       ('Spring Framework 6.1.0', 'Spring Framework 6.1.0 ist die aktuelle Version des Java-Anwendungsframeworks.',
        (SELECT id FROM technologies WHERE name = 'Spring')),
       ('Angular 17.0.0', 'Angular 17.0.0 ist die neueste Version des Webanwendungsframeworks von Google.',
        (SELECT id FROM technologies WHERE name = 'Angular')),
       ('Vue.js 3.3.4', 'Vue.js 3.3.4 ist die aktuelle Version des progressiven Frontend-Frameworks.',
        (SELECT id FROM technologies WHERE name = 'VueJS')),
       ('PHP 8.2.5', 'PHP 8.2.5 ist die neueste Version der Skriptsprache für Webentwicklung.',
        (SELECT id FROM technologies WHERE name = 'PHP')),
       ('Zend Framework 3.2.0', 'Zend Framework 3.2.0 ist die letzte Version des PHP-Frameworks.',
        (SELECT id FROM technologies WHERE name = 'Zend')),
       ('Laminas 3.3.0', 'Laminas 3.3.0 ist die aktuelle Version des Nachfolgers von Zend Framework.',
        (SELECT id FROM technologies WHERE name = 'Laminas')),
       ('Keycloak 23.0.1',
        'Keycloak 23.0.1 ist die neueste Version der Identitäts- und Zugriffsmanagementlösung, veröffentlicht im Mai 2025.',
        (SELECT id FROM technologies WHERE name = 'Keycloak')),
       ('Quarkus 3.0.0',
        'Quarkus 3.0.0 ist die neueste Version des Kubernetes-nativen Java-Frameworks, veröffentlicht im Jahr 2025.',
        (SELECT id FROM technologies WHERE name = 'Quarkus')),
       ('OpenShift 4.12',
        'OpenShift 4.12 ist die neueste Version der Kubernetes-basierten Plattform von Red Hat.',
        (SELECT id FROM technologies WHERE name = 'OpenShift')),
       ('Virtual Machines 1.0',
        'Virtual Machines 1.0 repräsentiert die aktuelle Standardversion der virtualisierten Rechenumgebungen.',
        (SELECT id FROM technologies WHERE name = 'Virtual Machines')),
       ('GKE 1.27',
        'GKE (Google Kubernetes Engine) Version 1.27 ist die aktuelle Version mit erweiterten Kubernetes-Funktionen.',
        (SELECT id FROM technologies WHERE name = 'GKE')),
       ('Jenkins 2.414',
        'Jenkins 2.414 ist die neueste LTS-Version des bekannten CI/CD-Automatisierungsservers.',
        (SELECT id FROM technologies WHERE name = 'Jenkins')),
       ('Selenium 4.11',
        'Selenium 4.11 ist die neueste Version des Frameworks für Webbrowser-Automatisierung.',
        (SELECT id FROM technologies WHERE name = 'Selenium'));